### ISSUE TITLE
Not an issue, but wanted to let you/others know about...

### ISSUE THREAD

**Issue by BogusException** [timeddilation/dbUpsert#2]
Postgresql now has:

https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-upsert/

It is not an elegant solution that is cross-RDBMS compatible, and might be considered "gauges instead of dummy lights", but the thinking looks to be along the same general lines:

> **Introduction to the PostgreSQL UPSERT**
> 
> Upsert is a combination of [update](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-update/) and [insert](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-insert/). The upsert allows you to update an existing row or insert a new one if it doesn’t exist.
> 
> PostgreSQL does not have the UPSERT statement but it supports the upsert operation via the INSERT...ON CONFLICT statement.
> 
> Here’s the basic syntax of the INSERT...ON CONFLICT statement:
> 
> INSERT INTO table_name (column1, column2, ...)
>   VALUES (value1, value2, ...)
>   ON CONFLICT (conflict_column)
>   DO NOTHING | DO UPDATE SET column1 = value1, column2 = value2, ...;
>   Code language: SQL (Structured Query Language) (sql)
> 
> **In this syntax:**
> 
> - table_name: This is the name of the table where you want to insert data.
> - (column1, column2, ...): The list of columns for which you provide values to insert into the table.
> - VALUES(value1, value2, ...): The values you want to insert into the specified columns (column1, column2, ...).
> - ON CONFLICT (conflict_column): This clause specifies the conflict target, which is the [unique constraint](https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-unique-constraint/) or [unique index](https://www.postgresqltutorial.com/postgresql-indexes/postgresql-unique-index/) that may cause a conflict.
> - DO NOTHING: This instructs PostgreSQL to do nothing when a conflict occurs.
> - DO UPDATE: This performs an update if a conflict occurs.
> - SET column = value1, column = value2, ...: This list of the columns to be updated and their corresponding values in case of conflict.

**Comment by timeddilation** [comment]
Hi there, thanks for feedback. Postgres has had this capability for a while, and in my first version of this package (before I published it) I used this version to handle upserts with postgres. However, when I moved to needing to use this for MS SQL as well, the same syntax does not exist, and I didn't want to have a different implementation for every flavor of SQL.

I chose the method that exists in this package because it's completely ANSI standard. It doesn't use any RDBMS-specific syntax, and therefore should work on all implementations of SQL. I haven't come back around to opening up the package to allow for all kinds of RDMBS's yet because I would need to redesign aspects of the implementation and documentation. I should get around to it one day though.
